# GitHub Pages + Minimal Mistakes 호환 설정
title: "AI 개발자 생존 가이드"
subtitle: "2023년에 잠들어 2025년에 깨어난 개발자의 AI 생태계 적응기"
name: "Mi NhanR"
description: "Vision AI Engineer의 실무 경험과 AI 도구 활용법"
url: "https://Mi-NhanR.github.io"
baseurl: ""
repository: "Mi-NhanR/Mi-NhanR.github.io"

# Remote theme (GitHub Pages 호환)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Author
author:
  name: "Mi NhanR"
  bio: "Vision AI Engineer & Scientist"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mi-NhanR"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins (GitHub Pages 허용 목록만)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
