# Site Settings
title: "AI 개발자 생존 가이드"
subtitle: "2023년에 잠들어 2025년에 깨어난 개발자의 AI 생태계 적응기"
name: "Mi NhanR"
description: "Vision AI Engineer의 실무 경험과 AI 도구 활용법"
url: "https://Mi-NhanR.github.io"
baseurl: ""
repository: "Mi-NhanR/Mi-NhanR.github.io"

# Site Author
author:
  name: "Mi NhanR"
  bio: "Vision AI Engineer & Scientist"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mi-NhanR"

# Reading Files
include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
